export const EXPLORE_POSTS_REQUEST = 'EXPLORE_POSTS_REQUEST';
export const EXPLORE_POSTS_SUCCESS = 'EXPLORE_POSTS_SUCCESS';
export const EXPLORE_POSTS_FAILURE = 'EXPLORE_POSTS_FAILURE';

export const CREATE_NEW_POST_REQUEST = 'CREATE_NEW_POST_REQUEST';
export const CREATE_NEW_POST_SUCCESS = 'CREATE_NEW_POST_SUCCESS';
export const CREATE_NEW_POST_FAILURE = 'CREATE_NEW_POST_FAILURE';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS';
export const POST_DETAILS_FAILURE = 'POST_DETAILS_FAILURE';

export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAILURE = 'LIKE_POST_FAILURE';
export const CLEAR_LIKE_POST_DATA = 'CLEAR_LIKE_POST_DATA';
