export const EXPLORE_POSTS_REQUEST = 'EXPLORE_POSTS_REQUEST';
export const EXPLORE_POSTS_SUCCESS = 'EXPLORE_POSTS_SUCCESS';
export const EXPLORE_POSTS_FAILURE = 'EXPLORE_POSTS_FAILURE';

export const CREATE_NEW_POST_REQUEST = 'CREATE_NEW_POST_REQUEST';
export const CREATE_NEW_POST_SUCCESS = 'CREATE_NEW_POST_SUCCESS';
export const CREATE_NEW_POST_FAILURE = 'CREATE_NEW_POST_FAILURE';
